### ISSUE TITLE
Completed

### ISSUE THREAD

**Issue by lumodon** [lumodon/Dianafinn-webdev#1]
## Description

Complete basic and advanced JavaScript Training on TreeHouse and FreeCodeCamp, a high quality interactive tutorial websites.

## Context

Do you feel like you are not able to effectively communicate with your team mates on your project? Ever wanted to become a great JavaScript developer? 

Well now you can get an AWESOME, SOLID FOUNDATION to help you with this journey. This one week long cycle will OVERLOAD and EXPAND your MIND. This project will allow you to have a better understanding of all future javascript goals. 

## Specifications

Javascript Tutorials:
- [x] JQuery Basics
- [x] JavaScript Basics
- [x] JavaScript Loops, Arrays and Objects
- [x] Node.js Basics
- [ ] Build a Simple Dynamic Site with Node.js
- [x] npm Basics
- [x] Express Basics

- [x] JavaScript Unit Testing
- [x] Build a REST API with Express
- [ ] Gulp Basics
- [ ] The Module Pattern in JavaScript
- [ ] Using JQuery Plugins

Databases:
- [ ] Modifying Data with SQL
- [x] Reporting with SQL
- [x] SQL Basics

- [x] The artifact produced is properly licensed, preferably with the [MIT license][mit-license].

# Stretch Goals
- [ ] Ember.js
- [x] Mongo Basics
- [ ] React
- [ ] Programming Step-by-Step: Object-Oriented JavaScript

## Deprecated
- [ ] Angular Basics

Can't do because Pro Account required:
- [ ] Deploy a Node Application to Heroku

---

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>
<br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

[mit-license]: https://opensource.org/licenses/MIT

**Comment by lumodon** [comment]
https://teamtreehouse.com/library/programming-stepbystep-objectoriented-javascript-part-1
https://teamtreehouse.com/library/programming-stepbystep-objectoriented-javascript-part-2

**Comment by DianaVashti** [comment]
Jquery - 2.5 hours

https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors
